version: '3.9'
services:
  app:
    container_name: accountsvc
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
    tty: true
    build:
      context: .
      dockerfile: ./script/Dockerfile
    ports:
      - 8081:8081
    restart: on-failure
    command: bash -c "
      /app/app -migrateup=true &&
      /app/app"
    networks:
      - ordersvc_carrent
networks:
  ordersvc_carrent:
    external: true
